export const initialModules = [
  {
    id: "DiscreteMathSets",
    title: "Sets in Discrete Math",
    description: "Learn about sets, subsets, and set operations.",
    modules: 10,
    lessons: [
      {
        id: "SetsIntro1",
        title: "Introduction",
        completed: false,
        prevLesson: "SetsIntro1",
        nextLesson: "SetsIntro2",
        content: "Introduction to sets with a video.",
      },
      {
        id: "SetsIntro2",
        title: "Ways of Representing Sets",
        completed: false,
        prevLesson: "SetsIntro1",
        nextLesson: "SetsIntro3",
        content: "Learn about set builder notation, interval, and roster.",
      },
      {
        id: "SetsIntro3",
        title: "Membership Table",
        completed: false,
        prevLesson: "SetsIntro2",
        nextLesson: "SetsIntro4",
        content: "Introduction to membership table for sets.",
      },
      {
        id: "SetsIntro4",
        title: "Venn Diagrams",
        completed: false,
        prevLesson: "SetsIntro3",
        nextLesson: "SetsIntro5",
        content: "Learn about Venn diagrams for sets.",
      },
      {
        id: "SetsIntro5",
        title: "Subsets",
        completed: false,
        prevLesson: "SetsIntro4",
        nextLesson: "SetsIntro6",
        content: "Introduction to subsets and their properties.",
      },
      {
        id: "SetsIntro6",
        title: "Cardinality",
        completed: false,
        prevLesson: "SetsIntro5",
        nextLesson: "SetsIntro7",
        content: "Learn about the size (cardinality) of a set.",
      },
      {
        id: "SetsIntro7",
        title: "Power Set",
        completed: false,
        prevLesson: "SetsIntro6",
        nextLesson: "SetsIntro8",
        content: "Introduction to power sets and their properties.",
      },
      {
        id: "SetsIntro8",
        title: "Cartesian Products",
        completed: false,
        prevLesson: "SetsIntro7",
        nextLesson: "SetsIntro9",
        content: "Learn about Cartesian products of sets.",
      },
      {
        id: "SetsIntro9",
        title: "Set Operations Introduction",
        completed: false,
        prevLesson: "SetsIntro8",
        nextLesson: "SetsIntro10",
        content: "Introduction to set operations.",
      },
      {
        id: "SetsIntro10",
        title: "Set Operations Overview",
        completed: false,
        prevLesson: "SetsIntro9",
        nextLesson: "SetOperationsIntro",
        content: "Overview of set operations such as union, intersection, etc.",
      },
    ],
  },
  {
    id: "SetOperationsIntro",
    title: "Set Operations",
    description:
      "Learn about set operations such as union, intersection, and more.",
    modules: 8,
    lessons: [
      {
        id: "SetOpsIntro1",
        title: "Introduction",
        completed: false,
        prevLesson: "SetOpsIntro1",
        nextLesson: "SetOpsIntro2",
        content: "Introduction to set operations.",
      },
      {
        id: "SetOpsIntro2",
        title: "Union and Intersection",
        completed: false,
        prevLesson: "SetOpsIntro1",
        nextLesson: "SetOpsIntro3",
        content: "Learn about union and intersection of sets.",
      },
      {
        id: "SetOpsIntro3",
        title: "Disjoint Sets",
        completed: false,
        prevLesson: "SetOpsIntro2",
        nextLesson: "SetOpsIntro4",
        content: "Learn about disjoint sets and their properties.",
      },
      {
        id: "SetOpsIntro4",
        title: "Universal Sets",
        completed: false,
        prevLesson: "SetOpsIntro3",
        nextLesson: "SetOpsIntro5",
        content: "Introduction to universal sets and their role in operations.",
      },
      {
        id: "SetOpsIntro5",
        title: "Singleton Sets",
        completed: false,
        prevLesson: "SetOpsIntro4",
        nextLesson: "SetOpsIntro6",
        content: "Learn about singleton sets.",
      },
      {
        id: "SetOpsIntro6",
        title: "Complements",
        completed: false,
        prevLesson: "SetOpsIntro5",
        nextLesson: "SetOpsIntro7",
        content: "Learn about complements of sets.",
      },
      {
        id: "SetOpsIntro7",
        title: "Set Difference",
        completed: false,
        prevLesson: "SetOpsIntro6",
        nextLesson: "SetOpsIntro8",
        content: "Learn about the difference between sets.",
      },
      {
        id: "SetOpsIntro8",
        title: "Exclusive OR",
        completed: false,
        prevLesson: "SetOpsIntro7",
        nextLesson: "SetOpsIntro9",
        content: "Learn about the exclusive OR operation in sets.",
      },
      {
        id: "SetOpsIntro9",
        title: "Set Identities",
        completed: false,
        prevLesson: "SetOpsIntro8",
        nextLesson: "SetOpsIntro10",
        content: "Introduction to set identities and their properties.",
      },
      {
        id: "SetOpsIntro10",
        title: "Venn Diagrams and Set Laws",
        completed: false,
        prevLesson: "SetOpsIntro9",
        nextLesson: "",
        content: "Using Venn diagrams to explain set laws and proofs.",
      },
    ],
  },
];
