export const initialModules = [
  {
    id: "AhsesiUniversitySets",
    title: "Sets in Discrete Math",
    description: "Learn about sets, subsets, and set operations.",
    modules: 10,
    lessons: [
      {
        id: "DefinitionAshesi1",
        title: "Introduction",
        completed: false,
        prevLesson: "",
        nextLesson: "DefinitionAshesi2",
        content: "This is the introduction to sets.",
      },
      {
        id: "DefinitionAshesi2",
        title: "Venn Diagrams",
        completed: false,
        prevLesson: "DefinitionAshesi1",
        nextLesson: "DefinitionAshesi3",
        content: "This is the introduction to Venn Diagrams.",
      },
      {
        id: "DefinitionAshesi3",
        title: "Subsets",
        completed: false,
        prevLesson: "DefinitionAshesi2",
        nextLesson: "DefinitionAshesi4",
        content: "This is the introduction to subsets.",
      },
      {
        id: "DefinitionAshesi4",
        title: "The size of a set",
        completed: false,
        prevLesson: "DefinitionAshesi3",
        nextLesson: "DefinitionAshesi5",
        content: "This is the introduction to the size of a set.",
      },
      {
        id: "DefinitionAshesi5",
        title: "Power Sets",
        completed: false,
        prevLesson: "DefinitionAshesi4",
        nextLesson: "DefinitionAshesi6",
        content: "This is the introduction to power sets.",
      },
      {
        id: "DefinitionAshesi6",
        title: "Power Sets",
        completed: false,
        prevLesson: "DefinitionAshesi5",
        nextLesson: "DefinitionAshesi7",
        content: "This is the introduction to power sets.",
      },
      {
        id: "DefinitionAshesi7",
        title: "Cartesian Product",
        completed: false,
        prevLesson: "DefinitionAshesi6",
        nextLesson: "DefinitionAshesi8",
        content: "This is the introduction to Cartesian Product.",
      },
      {
        id: "DefinitionAshesi8",
        title: "Power Sets",
        completed: false,
        prevLesson: "DefinitionAshesi7",
        nextLesson: "DefinitionAshesi9",
        content: "This is the introduction to power sets.",
      },
      {
        id: "DefinitionAshesi9",
        title: "Using Set Notation with Quantifiers",
        completed: false,
        prevLesson: "DefinitionAshesi8",
        nextLesson: "DefinitionAshesi10",
        content:
          "This is the introduction to using set notation with quantifiers.",
      },
      {
        id: "DefinitionAshesi10",
        title: "Truth Sets and Quantifiers",
        completed: false,
        prevLesson: "DefinitionAshesi9",
        nextLesson: "",
        content: "this is about truth sets",
      },
    ],
  },
  {
    id: "AhsesiUniversity",
    title: "Set Operations",
    description: "Learn about sets, subsets, set operations, and more.",
    modules: 8,
    lessons: [
      {
        id: "SetOperationsAshesi1",
        title: "Introduction",
        completed: false,
        prevLesson: "",
        nextLesson: "SetOperationsAshesi2",
        content: "Introduction to set operations",
      },
      {
        id: "SetOperationsAshesi2",
        title: "Set Identities",
        completed: false,
        prevLesson: "SetOperationsAshesi1",
        nextLesson: "SetOperationsAshesi3",
        content: "Introduction to set operations",
      },
      {
        id: "SetOperationsAshesi3",
        title: "Generalized Unions and Intersections",
        completed: false,
        prevLesson: "SetOperationsAshesi2",
        nextLesson: "SetOperationsAshesi4",
        content: "Introduction to set operations",
      },
      {
        id: "SetOperationsAshesi4",
        title: "Computer Representation of Sets",
        completed: false,
        prevLesson: "SetOperationsAshesi3",
        nextLesson: "SetOperationsAshesi5",
        content: "Introduction to set operations",
      },
      {
        id: "SetOperationsAshesi5",
        title: "Power Sets",
        completed: false,
        prevLesson: "SetOperationsAshesi4",
        nextLesson: "SetOperationsAshesi6",
        content: "Introduction to set operations",
      },
      {
        id: "DefinitionAshesi6",
        title: "Power Sets",
        completed: false,
        prevLesson: "SetOperationsAshesi5",
        nextLesson: "SetOperationsAshesi7",
        content: "Introduction to set operations",
      },
      {
        id: "SetOperationsAshesi7",
        title: "Cartesian Product",
        completed: false,
        prevLesson: "SetOperationsAshesi6",
        nextLesson: "SetOperationsAshesi8",
        content: "Introduction to set operations",
      },
      {
        id: "SetOperationsAshesi8",
        title: "Power Sets",
        completed: false,
        prevLesson: "SetOperationsAshesi7",
        nextLesson: "SetOperationsAshesi9",
        content: "Introduction to set operations",
      },
      {
        id: "SetOperationsAshesi9",
        title: "Using Set Notation with Quantifiers",
        completed: false,
        prevLesson: "SetOperationsAshesi8",
        nextLesson: "SetOperationsAshesi10",
        content: "Introduction to set operations",
      },
      {
        id: "SetOperationsAshesi10",
        title: "Truth Sets and Quantifiers",
        completed: false,
        prevLesson: "SetOperationsAshesi9",
        nextLesson: "",
        content: "Introduction to set operations",
      },
    ],
  },
];
