export const initialModules = [
  {
    id: "AshesiSets",
    title: "Sets in Discrete Math",
    description:
      "Learn about the foundational concepts of sets, subsets, and their properties.",
    modules: 8,
    lessons: [
      {
        id: "SetsIntro1",
        title: "Introduction to Sets",
        completed: false,
        prevLesson: "SetsIntro1",
        nextLesson: "SetsDescribing2",
        content:
          "Explore the basics of sets and their significance in mathematics.",
      },
      {
        id: "SetsDescribing2",
        title: "Describing Sets",
        completed: false,
        prevLesson: "SetsIntro1",
        nextLesson: "SetsEmptyUniversal3",
        content:
          "Learn various ways to describe sets, including set-builder and roster notation.",
      },
      {
        id: "SetsEmptyUniversal3",
        title: "Empty Set and Universal Set",
        completed: false,
        prevLesson: "SetsDescribing2",
        nextLesson: "SetsSubsetsEquality4",
        content:
          "Understand the concepts of the empty set and the universal set.",
      },
      {
        id: "SetsSubsetsEquality4",
        title: "Subsets and Set Equality",
        completed: false,
        prevLesson: "SetsEmptyUniversal3",
        nextLesson: "SetsCardinality5",
        content: "Examine subsets and learn how to determine set equality.",
      },
      {
        id: "SetsCardinality5",
        title: "Cardinality of Sets",
        completed: false,
        prevLesson: "SetsSubsetsEquality4",
        nextLesson: "SetsPower6",
        content: "Learn to calculate the size or cardinality of a set.",
      },
      {
        id: "SetsPower6",
        title: "Power Set",
        completed: false,
        prevLesson: "SetsCardinality5",
        nextLesson: "SetsTuple7",
        content: "Explore the concept of the power set and its properties.",
      },
      {
        id: "SetsTuple7",
        title: "Tuple",
        completed: false,
        prevLesson: "SetsPower6",
        nextLesson: "SetsCartesian8",
        content: "Understand tuples and their role in ordered collections.",
      },
      {
        id: "SetsCartesian8",
        title: "Cartesian Products",
        completed: false,
        prevLesson: "SetsTuple7",
        nextLesson: "SetsCartesian8",
        content: "Learn how to create Cartesian products of two or more sets.",
      },
    ],
  },
  {
    id: "AshesiSetOperations",
    title: "Set Operations",
    description: "Master operations on sets and their different properties.",
    modules: 8,
    lessons: [
      {
        id: "SetOpsIntro1",
        title: "Introduction to Set Operations",
        completed: false,
        prevLesson: "SetOpsIntro1",
        nextLesson: "SetOpsUnion2",
        content: "Discover the importance of operations on sets.",
      },
      {
        id: "SetOpsUnion2",
        title: "Union",
        completed: false,
        prevLesson: "SetOpsIntro1",
        nextLesson: "SetOpsIntersection3",
        content: "Learn how to find the union of two or more sets.",
      },
      {
        id: "SetOpsIntersection3",
        title: "Intersection",
        completed: false,
        prevLesson: "SetOpsUnion2",
        nextLesson: "SetOpsDisjoint4",
        content: "Understand the intersection of sets and its applications.",
      },
      {
        id: "SetOpsDisjoint4",
        title: "Disjoint Sets",
        completed: false,
        prevLesson: "SetOpsIntersection3",
        nextLesson: "SetOpsSingleton5",
        content: "Learn about disjoint sets and their characteristics.",
      },
      {
        id: "SetOpsSingleton5",
        title: "Singleton and Universal Sets",
        completed: false,
        prevLesson: "SetOpsDisjoint4",
        nextLesson: "SetOpsComplement6",
        content: "Explore singleton and universal sets in detail.",
      },
      {
        id: "SetOpsComplement6",
        title: "Complements",
        completed: false,
        prevLesson: "SetOpsSingleton5",
        nextLesson: "SetOpsDifference7",
        content: "Understand the concept of complements in set theory.",
      },
      {
        id: "SetOpsDifference7",
        title: "Difference",
        completed: false,
        prevLesson: "SetOpsComplement6",
        nextLesson: "SetOpsXOR8",
        content: "Learn how to calculate the difference between sets.",
      },
      {
        id: "SetOpsXOR8",
        title: "Exclusive OR (XOR)",
        completed: false,
        prevLesson: "SetOpsDifference7",
        nextLesson: "SetOpsXOR8",
        content: "Examine the concept of XOR and its usage in set operations.",
      },
    ],
  },
  {
    id: "AshesiSetIdentities",
    title: "Set Identities",
    description:
      "Understand and apply set identities, proofs, and their representations.",
    modules: 4,
    lessons: [
      {
        id: "SetIdentitiesTable1",
        title: "Table of Operations",
        completed: false,
        prevLesson: "SetIdentitiesTable1",
        nextLesson: "SetIdentitiesProofs2",
        content: "Review the table of set operations and their identities.",
      },
      {
        id: "SetIdentitiesProofs2",
        title: "Explanation of Laws and Proofs",
        completed: false,
        prevLesson: "SetIdentitiesTable1",
        nextLesson: "SetIdentitiesVenn3",
        content: "Learn and prove set laws using mathematical reasoning.",
      },
      {
        id: "SetIdentitiesVenn3",
        title: "Using Venn Diagrams",
        completed: false,
        prevLesson: "SetIdentitiesProofs2",
        nextLesson: "SetIdentitiesComputer4",
        content: "Visualize and explain set laws using Venn diagrams.",
      },
      {
        id: "SetIdentitiesComputer4",
        title: "Computer Representation of Sets",
        completed: false,
        prevLesson: "SetIdentitiesVenn3",
        nextLesson: "SetIdentitiesComputer4",
        content:
          "Explore how sets and their operations are represented in computers.",
      },
    ],
  },
];
